### ISSUE TITLE
No way of converting local files to xml

### ISSUE THREAD

**Issue by ieldib** [vinitkumar/json2xml#3]
How can we do this locally ? It looks like this depends heavily on urllib which errors out when you try and do this locally. Any advice ?

**Comment by vinitkumar** [comment]
Well,  I never thought of adding support for converting local files. But since now it has come up, I think it is a good idea to integrate this feature to make it more useful. I will probably spend sometime in the couple of days to implement this feature. If you are in a hurry, override this method to read from local json files and you should be good to go.

```python
def json2xml(self):
        data = simplejson.load(urllib.urlopen(self.url))
        #override data to read from local xml files. 
        if data:
            xmldata = dict2xml.dict2xml(data)
            xml = BeautifulStoneSoup(xmldata)
            return xml
```

**Comment by vinitkumar** [comment]
@ieldib The latest master has the feature to convert both local and files from URL. Closing this issue for now. Please reopen if you face any problem.
